[package]
name = "miden-crypto"
version = "0.10.0"
description = "Miden Cryptographic primitives"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/crypto"
documentation = "https://docs.rs/miden-crypto/0.10.0"
categories = ["cryptography", "no-std"]
keywords = ["miden", "crypto", "hash", "merkle"]
edition = "2021"
rust-version = "1.80"

[[bin]]
name = "miden-crypto"
path = "src/main.rs"
bench = false
doctest = false
required-features = ["executable"]

[[bench]]
name = "hash"
harness = false

[[bench]]
name = "smt"
harness = false

[[bench]]
name = "store"
harness = false

[features]
default = ["std"]
executable = ["dep:clap", "dep:rand-utils", "std"]
serde = ["dep:serde", "serde?/alloc", "winter-math/serde"]
std = [
    "blake3/std",
    "dep:cc",
    "rand/std",
    "rand/std_rng",
    "winter-crypto/std",
    "winter-math/std",
    "winter-utils/std",
]

[dependencies]
blake3 = { version = "1.5", default-features = false }
clap = { version = "4.5", optional = true, features = ["derive"] }
num = { version = "0.4", default-features = false, features = ["alloc", "libm"] }
num-complex = { version = "0.4", default-features = false }
rand = { version = "0.8", default-features = false }
rand_core = { version = "0.6", default-features = false }
rand-utils = { version = "0.9", package = "winter-rand-utils", optional = true }
serde = { version = "1.0", default-features = false, optional = true, features = ["derive"] }
sha3 = { version = "0.10", default-features = false }
winter-crypto = { version = "0.9", default-features = false }
winter-math = { version = "0.9", default-features = false }
winter-utils = { version = "0.9", default-features = false }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
getrandom = { version = "0.2", features = ["js"] }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
proptest = "1.4"
rand_chacha = { version = "0.3", default-features = false }
rand-utils = { version = "0.9", package = "winter-rand-utils" }
seq-macro = { version = "0.3" }

[build-dependencies]
cc = { version = "1.0", optional = true, features = ["parallel"] }
glob = "0.3"

[patch.crates-io]
winter-prover = { git = "https://github.com/GopherJ/winterfell", rev = "8dec862fbb3cb5bc98856dafade4486c7355d42b" }
winter-air = { git = "https://github.com/GopherJ/winterfell", rev = "8dec862fbb3cb5bc98856dafade4486c7355d42b" }
winter-utils = { git = "https://github.com/GopherJ/winterfell", rev = "8dec862fbb3cb5bc98856dafade4486c7355d42b" }
winter-verifier = { git = "https://github.com/GopherJ/winterfell", rev = "8dec862fbb3cb5bc98856dafade4486c7355d42b" }
winter-fri = { git = "https://github.com/GopherJ/winterfell", rev = "8dec862fbb3cb5bc98856dafade4486c7355d42b" }
winter-crypto = { git = "https://github.com/GopherJ/winterfell", rev = "8dec862fbb3cb5bc98856dafade4486c7355d42b" }
winter-math = { git = "https://github.com/GopherJ/winterfell", rev = "8dec862fbb3cb5bc98856dafade4486c7355d42b" }
winter-rand-utils = { git = "https://github.com/GopherJ/winterfell", rev = "8dec862fbb3cb5bc98856dafade4486c7355d42b" }

